name = "Neurthino"
uuid = "ea3506b1-7c4e-45d8-9afb-6e8d18a7dde4"
authors = ["Johannes Schumann", "Tamás Gál"]
version = "1.0.1"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AxisArrays = "^0.4"
DocStringExtensions = "^0.8"
LRUCache = "1"
LightGraphs = "1"
Polynomials = "1 - 3"
StaticArrays = "1"
julia = "^1.3"

[extras]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HDF5"]
